[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[build.environment]
  NODE_VERSION = "18"

# 重定向規則
[[redirects]]
  from = "/privacy"
  to = "/legal/privacy-policy.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/legal/terms-of-service.html"
  status = 301

[[redirects]]
  from = "/cookies"
  to = "/legal/cookie-policy.html"
  status = 301

# SPA 重定向（如果需要）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 安全標頭
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://www.google-analytics.com; frame-src https://www.google.com; object-src 'none';"

# Cache 設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# APK 文件 MIME 類型
[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"

# 錯誤頁面
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# 表單處理（如果需要）
[forms]
  settings = { protected = false } 